version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: monthly
    groups:
      python:
        patterns: ["*"]

  - package-ecosystem: bun
    directory: /
    schedule:
      interval: monthly
    groups:
      frontend:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: monthly
    groups:
      container:
        patterns: ["*"]

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: monthly
    groups:
      compose:
        patterns: ["*"]
