// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AgentCreate
 */
export type AgentCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Password
     */
    password: string;
    /**
     * Is Active
     */
    is_active?: boolean;
};

/**
 * AgentResetPassword
 */
export type AgentResetPassword = {
    /**
     * New Password
     */
    new_password: string;
};

/**
 * AgentUpdate
 */
export type AgentUpdate = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * New Password
     */
    new_password?: string | null;
};

/**
 * AssignmentUpdate
 */
export type AssignmentUpdate = {
    /**
     * Assigned To Id
     */
    assigned_to_id?: string | null;
};

/**
 * AttachmentDownloadRequest
 */
export type AttachmentDownloadRequest = {
    /**
     * Reference
     */
    reference: string;
    /**
     * Reporter Email
     */
    reporter_email: string;
    /**
     * Attachment Id
     */
    attachment_id: string;
};

/**
 * AttachmentPublic
 */
export type AttachmentPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Media Type
     */
    media_type: string;
    /**
     * Byte Count
     */
    byte_count: number;
    /**
     * Width
     */
    width: number;
    /**
     * Height
     */
    height: number;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_public-create_case
 */
export type Body_public_create_case = {
    /**
     * Submission Id
     */
    submission_id: string;
    /**
     * Reporter Name
     */
    reporter_name: string;
    /**
     * Reporter Email
     */
    reporter_email: string;
    /**
     * Category Id
     */
    category_id: string;
    /**
     * Subject
     */
    subject: string;
    /**
     * Description
     */
    description: string;
    /**
     * Location Text
     */
    location_text: string;
    /**
     * Photos
     */
    photos?: Array<Blob | File> | null;
};

/**
 * Body_public-create_public_message
 */
export type Body_public_create_public_message = {
    /**
     * Reference
     */
    reference: string;
    /**
     * Reporter Email
     */
    reporter_email: string;
    /**
     * Body Markdown
     */
    body_markdown: string;
    /**
     * Photos
     */
    photos?: Array<Blob | File> | null;
};

/**
 * Body_staff-create_message
 */
export type Body_staff_create_message = {
    /**
     * Body Markdown
     */
    body_markdown?: string;
    visibility?: Visibility;
    /**
     * Photos
     */
    photos?: Array<Blob | File> | null;
};

/**
 * CaseCredentials
 */
export type CaseCredentials = {
    /**
     * Reference
     */
    reference: string;
    /**
     * Reporter Email
     */
    reporter_email: string;
};

/**
 * CaseEventPublic
 */
export type CaseEventPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Event Type
     */
    event_type: string;
    /**
     * Summary
     */
    summary: string;
    from_status: CaseStatus | null;
    to_status: CaseStatus | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * CaseMessagePublic
 */
export type CaseMessagePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Author Label
     */
    author_label: string;
    /**
     * Body Html
     */
    body_html: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Attachments
     */
    attachments?: Array<AttachmentPublic>;
};

/**
 * CasePriority
 */
export type CasePriority = 'low' | 'normal' | 'high' | 'urgent';

/**
 * CasePublic
 */
export type CasePublic = {
    /**
     * Reference
     */
    reference: string;
    category: ServiceCategoryPublic;
    /**
     * Subject
     */
    subject: string;
    /**
     * Description
     */
    description: string;
    /**
     * Location Text
     */
    location_text: string;
    status: CaseStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Attachments
     */
    attachments: Array<AttachmentPublic>;
    /**
     * Messages
     */
    messages: Array<CaseMessagePublic>;
    /**
     * Events
     */
    events: Array<CaseEventPublic>;
};

/**
 * CaseReceipt
 */
export type CaseReceipt = {
    /**
     * Reference
     */
    reference: string;
    status: CaseStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Reporter Email Masked
     */
    reporter_email_masked: string;
};

/**
 * CaseStatus
 */
export type CaseStatus = 'submitted' | 'triaged' | 'in_progress' | 'waiting_on_reporter' | 'resolved' | 'closed';

/**
 * ClassificationUpdate
 */
export type ClassificationUpdate = {
    /**
     * Category Id
     */
    category_id?: string | null;
    priority?: CasePriority | null;
};

/**
 * ClosureReason
 */
export type ClosureReason = 'resolved' | 'duplicate' | 'out_of_scope' | 'withdrawn';

/**
 * DashboardStats
 */
export type DashboardStats = {
    /**
     * Mine
     */
    mine: number;
    /**
     * Unassigned
     */
    unassigned: number;
    /**
     * Overdue
     */
    overdue: number;
    /**
     * Open Total
     */
    open_total: number;
    /**
     * Resolved Last 7 Days
     */
    resolved_last_7_days: number;
};

/**
 * ExportCreate
 */
export type ExportCreate = {
    kind: ExportKind;
    /**
     * Idempotency Key
     */
    idempotency_key: string;
    /**
     * Case Id
     */
    case_id?: string | null;
    /**
     * Filters
     */
    filters?: {
        [key: string]: string;
    };
};

/**
 * ExportKind
 */
export type ExportKind = 'case_pdf' | 'cases_csv';

/**
 * ExportPublic
 */
export type ExportPublic = {
    /**
     * Id
     */
    id: string;
    kind: ExportKind;
    status: JobStatus;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ExportsPublic
 */
export type ExportsPublic = {
    /**
     * Data
     */
    data: Array<ExportPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JobStatus
 */
export type JobStatus = 'queued' | 'running' | 'ready' | 'failed' | 'expired';

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * ServiceCategoryAdmin
 */
export type ServiceCategoryAdmin = {
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Name
     */
    name: string;
    /**
     * Summary
     */
    summary: string;
    /**
     * Guidance Html
     */
    guidance_html: string;
    /**
     * Response Target Hours
     */
    response_target_hours: number;
    /**
     * Sort Order
     */
    sort_order: number;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Guidance Markdown
     */
    guidance_markdown: string;
};

/**
 * ServiceCategoryCreate
 */
export type ServiceCategoryCreate = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Name
     */
    name: string;
    /**
     * Summary
     */
    summary: string;
    /**
     * Guidance Markdown
     */
    guidance_markdown: string;
    /**
     * Response Target Hours
     */
    response_target_hours: number;
    /**
     * Sort Order
     */
    sort_order?: number;
    /**
     * Is Active
     */
    is_active?: boolean;
};

/**
 * ServiceCategoryPublic
 */
export type ServiceCategoryPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Name
     */
    name: string;
    /**
     * Summary
     */
    summary: string;
    /**
     * Guidance Html
     */
    guidance_html: string;
    /**
     * Response Target Hours
     */
    response_target_hours: number;
    /**
     * Sort Order
     */
    sort_order: number;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * ServiceCategoryUpdate
 */
export type ServiceCategoryUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Summary
     */
    summary?: string | null;
    /**
     * Guidance Markdown
     */
    guidance_markdown?: string | null;
    /**
     * Response Target Hours
     */
    response_target_hours?: number | null;
    /**
     * Sort Order
     */
    sort_order?: number | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * ServicesAdmin
 */
export type ServicesAdmin = {
    /**
     * Data
     */
    data: Array<ServiceCategoryAdmin>;
    /**
     * Count
     */
    count: number;
};

/**
 * ServicesPublic
 */
export type ServicesPublic = {
    /**
     * Data
     */
    data: Array<ServiceCategoryPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * SitePublic
 */
export type SitePublic = {
    /**
     * Organization Name
     */
    organization_name: string;
    /**
     * Service Area
     */
    service_area: string;
    /**
     * Timezone
     */
    timezone: string;
    /**
     * Introduction Html
     */
    introduction_html: string;
    /**
     * Webhooks Enabled
     */
    webhooks_enabled: boolean;
};

/**
 * SiteSettingsPublic
 */
export type SiteSettingsPublic = {
    /**
     * Organization Name
     */
    organization_name: string;
    /**
     * Service Area
     */
    service_area: string;
    /**
     * Timezone
     */
    timezone: string;
    /**
     * Introduction Html
     */
    introduction_html: string;
    /**
     * Webhooks Enabled
     */
    webhooks_enabled: boolean;
    /**
     * Introduction Markdown
     */
    introduction_markdown: string;
};

/**
 * SiteSettingsUpdate
 */
export type SiteSettingsUpdate = {
    /**
     * Organization Name
     */
    organization_name: string;
    /**
     * Service Area
     */
    service_area: string;
    /**
     * Timezone
     */
    timezone: string;
    /**
     * Introduction Markdown
     */
    introduction_markdown: string;
};

/**
 * StaffCasePublic
 */
export type StaffCasePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Reference
     */
    reference: string;
    /**
     * Reporter Name
     */
    reporter_name: string;
    /**
     * Reporter Email
     */
    reporter_email: string;
    category: ServiceCategoryPublic;
    /**
     * Subject
     */
    subject: string;
    /**
     * Description
     */
    description: string;
    /**
     * Location Text
     */
    location_text: string;
    status: CaseStatus;
    priority: CasePriority;
    assigned_to: UserPublic | null;
    /**
     * Target Resolution At
     */
    target_resolution_at: string;
    /**
     * Resolved At
     */
    resolved_at: string | null;
    /**
     * Closed At
     */
    closed_at: string | null;
    closure_reason: ClosureReason | null;
    /**
     * Duplicate Case Id
     */
    duplicate_case_id: string | null;
    /**
     * Version
     */
    version: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Attachments
     */
    attachments: Array<AttachmentPublic>;
    /**
     * Messages
     */
    messages: Array<CaseMessagePublic>;
    /**
     * Events
     */
    events: Array<CaseEventPublic>;
};

/**
 * StaffCasesPublic
 */
export type StaffCasesPublic = {
    /**
     * Data
     */
    data: Array<StaffCasePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * TransitionRequest
 */
export type TransitionRequest = {
    status: CaseStatus;
    /**
     * Summary Markdown
     */
    summary_markdown: string;
    closure_reason?: ClosureReason | null;
    /**
     * Duplicate Case Id
     */
    duplicate_case_id?: string | null;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Visibility
 */
export type Visibility = 'public' | 'private';

/**
 * WebhookCreate
 */
export type WebhookCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Url
     */
    url: string;
    /**
     * Subscribed Events
     */
    subscribed_events: Array<string>;
};

/**
 * WebhookCreated
 */
export type WebhookCreated = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Url
     */
    url: string;
    /**
     * Subscribed Events
     */
    subscribed_events: Array<string>;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Signing Secret
     */
    signing_secret: string;
};

/**
 * WebhookPublic
 */
export type WebhookPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Url
     */
    url: string;
    /**
     * Subscribed Events
     */
    subscribed_events: Array<string>;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * WebhookUpdate
 */
export type WebhookUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Url
     */
    url?: string | null;
    /**
     * Subscribed Events
     */
    subscribed_events?: Array<string> | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * WebhooksPublic
 */
export type WebhooksPublic = {
    /**
     * Data
     */
    data: Array<WebhookPublic>;
    /**
     * Count
     */
    count: number;
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type publicGetSiteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/public/site';
};

export type publicGetSiteResponses = {
    /**
     * Successful Response
     */
    200: SitePublic;
};

export type publicGetSiteResponse = publicGetSiteResponses[keyof publicGetSiteResponses];

export type publicListServicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/public/services';
};

export type publicListServicesResponses = {
    /**
     * Successful Response
     */
    200: ServicesPublic;
};

export type publicListServicesResponse = publicListServicesResponses[keyof publicListServicesResponses];

export type publicGetServiceData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/public/services/{slug}';
};

export type publicGetServiceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type publicGetServiceError = publicGetServiceErrors[keyof publicGetServiceErrors];

export type publicGetServiceResponses = {
    /**
     * Successful Response
     */
    200: ServiceCategoryPublic;
};

export type publicGetServiceResponse = publicGetServiceResponses[keyof publicGetServiceResponses];

export type publicCreateCaseData = {
    body: Body_public_create_case;
    path?: never;
    query?: never;
    url: '/api/v1/public/cases';
};

export type publicCreateCaseErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type publicCreateCaseError = publicCreateCaseErrors[keyof publicCreateCaseErrors];

export type publicCreateCaseResponses = {
    /**
     * Successful Response
     */
    201: CaseReceipt;
};

export type publicCreateCaseResponse = publicCreateCaseResponses[keyof publicCreateCaseResponses];

export type publicLookupCaseData = {
    body: CaseCredentials;
    path?: never;
    query?: never;
    url: '/api/v1/public/cases/lookup';
};

export type publicLookupCaseErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type publicLookupCaseError = publicLookupCaseErrors[keyof publicLookupCaseErrors];

export type publicLookupCaseResponses = {
    /**
     * Successful Response
     */
    200: CasePublic;
};

export type publicLookupCaseResponse = publicLookupCaseResponses[keyof publicLookupCaseResponses];

export type publicCreatePublicMessageData = {
    body: Body_public_create_public_message;
    path?: never;
    query?: never;
    url: '/api/v1/public/cases/messages';
};

export type publicCreatePublicMessageErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type publicCreatePublicMessageError = publicCreatePublicMessageErrors[keyof publicCreatePublicMessageErrors];

export type publicCreatePublicMessageResponses = {
    /**
     * Successful Response
     */
    201: CaseMessagePublic;
};

export type publicCreatePublicMessageResponse = publicCreatePublicMessageResponses[keyof publicCreatePublicMessageResponses];

export type publicDownloadAttachmentData = {
    body: AttachmentDownloadRequest;
    path?: never;
    query?: never;
    url: '/api/v1/public/attachments/download';
};

export type publicDownloadAttachmentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type publicDownloadAttachmentError = publicDownloadAttachmentErrors[keyof publicDownloadAttachmentErrors];

export type publicDownloadAttachmentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type staffGetDashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/staff/dashboard';
};

export type staffGetDashboardResponses = {
    /**
     * Successful Response
     */
    200: DashboardStats;
};

export type staffGetDashboardResponse = staffGetDashboardResponses[keyof staffGetDashboardResponses];

export type staffListCasesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Status
         */
        status?: CaseStatus | null;
        /**
         * Priority
         */
        priority?: CasePriority | null;
        /**
         * Assignment
         */
        assignment?: string | null;
        /**
         * Search
         */
        search?: string | null;
    };
    url: '/api/v1/staff/cases';
};

export type staffListCasesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type staffListCasesError = staffListCasesErrors[keyof staffListCasesErrors];

export type staffListCasesResponses = {
    /**
     * Successful Response
     */
    200: StaffCasesPublic;
};

export type staffListCasesResponse = staffListCasesResponses[keyof staffListCasesResponses];

export type staffGetCaseData = {
    body?: never;
    path: {
        /**
         * Case Id
         */
        case_id: string;
    };
    query?: never;
    url: '/api/v1/staff/cases/{case_id}';
};

export type staffGetCaseErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type staffGetCaseError = staffGetCaseErrors[keyof staffGetCaseErrors];

export type staffGetCaseResponses = {
    /**
     * Successful Response
     */
    200: StaffCasePublic;
};

export type staffGetCaseResponse = staffGetCaseResponses[keyof staffGetCaseResponses];

export type staffUpdateAssignmentData = {
    body: AssignmentUpdate;
    headers?: {
        /**
         * If-Match
         */
        'if-match'?: string | null;
    };
    path: {
        /**
         * Case Id
         */
        case_id: string;
    };
    query?: never;
    url: '/api/v1/staff/cases/{case_id}/assignment';
};

export type staffUpdateAssignmentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type staffUpdateAssignmentError = staffUpdateAssignmentErrors[keyof staffUpdateAssignmentErrors];

export type staffUpdateAssignmentResponses = {
    /**
     * Successful Response
     */
    200: StaffCasePublic;
};

export type staffUpdateAssignmentResponse = staffUpdateAssignmentResponses[keyof staffUpdateAssignmentResponses];

export type staffUpdateClassificationData = {
    body: ClassificationUpdate;
    headers?: {
        /**
         * If-Match
         */
        'if-match'?: string | null;
    };
    path: {
        /**
         * Case Id
         */
        case_id: string;
    };
    query?: never;
    url: '/api/v1/staff/cases/{case_id}/classification';
};

export type staffUpdateClassificationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type staffUpdateClassificationError = staffUpdateClassificationErrors[keyof staffUpdateClassificationErrors];

export type staffUpdateClassificationResponses = {
    /**
     * Successful Response
     */
    200: StaffCasePublic;
};

export type staffUpdateClassificationResponse = staffUpdateClassificationResponses[keyof staffUpdateClassificationResponses];

export type staffUpdateStatusData = {
    body: TransitionRequest;
    headers?: {
        /**
         * If-Match
         */
        'if-match'?: string | null;
    };
    path: {
        /**
         * Case Id
         */
        case_id: string;
    };
    query?: never;
    url: '/api/v1/staff/cases/{case_id}/transition';
};

export type staffUpdateStatusErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type staffUpdateStatusError = staffUpdateStatusErrors[keyof staffUpdateStatusErrors];

export type staffUpdateStatusResponses = {
    /**
     * Successful Response
     */
    200: StaffCasePublic;
};

export type staffUpdateStatusResponse = staffUpdateStatusResponses[keyof staffUpdateStatusResponses];

export type staffCreateMessageData = {
    body?: Body_staff_create_message;
    headers?: {
        /**
         * If-Match
         */
        'if-match'?: string | null;
    };
    path: {
        /**
         * Case Id
         */
        case_id: string;
    };
    query?: never;
    url: '/api/v1/staff/cases/{case_id}/messages';
};

export type staffCreateMessageErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type staffCreateMessageError = staffCreateMessageErrors[keyof staffCreateMessageErrors];

export type staffCreateMessageResponses = {
    /**
     * Successful Response
     */
    201: StaffCasePublic;
};

export type staffCreateMessageResponse = staffCreateMessageResponses[keyof staffCreateMessageResponses];

export type staffDownloadAttachmentData = {
    body?: never;
    path: {
        /**
         * Attachment Id
         */
        attachment_id: string;
    };
    query?: never;
    url: '/api/v1/staff/attachments/{attachment_id}';
};

export type staffDownloadAttachmentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type staffDownloadAttachmentError = staffDownloadAttachmentErrors[keyof staffDownloadAttachmentErrors];

export type staffDownloadAttachmentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type staffListExportsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/staff/exports';
};

export type staffListExportsResponses = {
    /**
     * Successful Response
     */
    200: ExportsPublic;
};

export type staffListExportsResponse = staffListExportsResponses[keyof staffListExportsResponses];

export type staffCreateExportData = {
    body: ExportCreate;
    path?: never;
    query?: never;
    url: '/api/v1/staff/exports';
};

export type staffCreateExportErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type staffCreateExportError = staffCreateExportErrors[keyof staffCreateExportErrors];

export type staffCreateExportResponses = {
    /**
     * Successful Response
     */
    202: ExportPublic;
};

export type staffCreateExportResponse = staffCreateExportResponses[keyof staffCreateExportResponses];

export type staffGetExportData = {
    body?: never;
    path: {
        /**
         * Export Id
         */
        export_id: string;
    };
    query?: never;
    url: '/api/v1/staff/exports/{export_id}';
};

export type staffGetExportErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type staffGetExportError = staffGetExportErrors[keyof staffGetExportErrors];

export type staffGetExportResponses = {
    /**
     * Successful Response
     */
    200: ExportPublic;
};

export type staffGetExportResponse = staffGetExportResponses[keyof staffGetExportResponses];

export type staffDownloadExportData = {
    body?: never;
    path: {
        /**
         * Export Id
         */
        export_id: string;
    };
    query?: never;
    url: '/api/v1/staff/exports/{export_id}/download';
};

export type staffDownloadExportErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type staffDownloadExportError = staffDownloadExportErrors[keyof staffDownloadExportErrors];

export type staffDownloadExportResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type adminListAgentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/agents';
};

export type adminListAgentsResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type adminListAgentsResponse = adminListAgentsResponses[keyof adminListAgentsResponses];

export type adminCreateAgentData = {
    body: AgentCreate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/agents';
};

export type adminCreateAgentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminCreateAgentError = adminCreateAgentErrors[keyof adminCreateAgentErrors];

export type adminCreateAgentResponses = {
    /**
     * Successful Response
     */
    201: UserPublic;
};

export type adminCreateAgentResponse = adminCreateAgentResponses[keyof adminCreateAgentResponses];

export type adminUpdateAgentData = {
    body: AgentUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/agents/{user_id}';
};

export type adminUpdateAgentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminUpdateAgentError = adminUpdateAgentErrors[keyof adminUpdateAgentErrors];

export type adminUpdateAgentResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type adminUpdateAgentResponse = adminUpdateAgentResponses[keyof adminUpdateAgentResponses];

export type adminResetAgentPasswordData = {
    body: AgentResetPassword;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/agents/{user_id}/reset-password';
};

export type adminResetAgentPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminResetAgentPasswordError = adminResetAgentPasswordErrors[keyof adminResetAgentPasswordErrors];

export type adminResetAgentPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type adminResetAgentPasswordResponse = adminResetAgentPasswordResponses[keyof adminResetAgentPasswordResponses];

export type adminGetSiteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/site';
};

export type adminGetSiteResponses = {
    /**
     * Successful Response
     */
    200: SiteSettingsPublic;
};

export type adminGetSiteResponse = adminGetSiteResponses[keyof adminGetSiteResponses];

export type adminUpdateSiteData = {
    body: SiteSettingsUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/site';
};

export type adminUpdateSiteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminUpdateSiteError = adminUpdateSiteErrors[keyof adminUpdateSiteErrors];

export type adminUpdateSiteResponses = {
    /**
     * Successful Response
     */
    200: SiteSettingsPublic;
};

export type adminUpdateSiteResponse = adminUpdateSiteResponses[keyof adminUpdateSiteResponses];

export type adminListServicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/services';
};

export type adminListServicesResponses = {
    /**
     * Successful Response
     */
    200: ServicesAdmin;
};

export type adminListServicesResponse = adminListServicesResponses[keyof adminListServicesResponses];

export type adminCreateServiceData = {
    body: ServiceCategoryCreate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/services';
};

export type adminCreateServiceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminCreateServiceError = adminCreateServiceErrors[keyof adminCreateServiceErrors];

export type adminCreateServiceResponses = {
    /**
     * Successful Response
     */
    201: ServiceCategoryPublic;
};

export type adminCreateServiceResponse = adminCreateServiceResponses[keyof adminCreateServiceResponses];

export type adminUpdateServiceData = {
    body: ServiceCategoryUpdate;
    path: {
        /**
         * Service Id
         */
        service_id: string;
    };
    query?: never;
    url: '/api/v1/admin/services/{service_id}';
};

export type adminUpdateServiceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminUpdateServiceError = adminUpdateServiceErrors[keyof adminUpdateServiceErrors];

export type adminUpdateServiceResponses = {
    /**
     * Successful Response
     */
    200: ServiceCategoryPublic;
};

export type adminUpdateServiceResponse = adminUpdateServiceResponses[keyof adminUpdateServiceResponses];

export type adminListWebhooksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/webhooks';
};

export type adminListWebhooksResponses = {
    /**
     * Successful Response
     */
    200: WebhooksPublic;
};

export type adminListWebhooksResponse = adminListWebhooksResponses[keyof adminListWebhooksResponses];

export type adminCreateWebhookData = {
    body: WebhookCreate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/webhooks';
};

export type adminCreateWebhookErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminCreateWebhookError = adminCreateWebhookErrors[keyof adminCreateWebhookErrors];

export type adminCreateWebhookResponses = {
    /**
     * Successful Response
     */
    201: WebhookCreated;
};

export type adminCreateWebhookResponse = adminCreateWebhookResponses[keyof adminCreateWebhookResponses];

export type adminUpdateWebhookData = {
    body: WebhookUpdate;
    path: {
        /**
         * Endpoint Id
         */
        endpoint_id: string;
    };
    query?: never;
    url: '/api/v1/admin/webhooks/{endpoint_id}';
};

export type adminUpdateWebhookErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminUpdateWebhookError = adminUpdateWebhookErrors[keyof adminUpdateWebhookErrors];

export type adminUpdateWebhookResponses = {
    /**
     * Successful Response
     */
    200: WebhookPublic;
};

export type adminUpdateWebhookResponse = adminUpdateWebhookResponses[keyof adminUpdateWebhookResponses];

export type adminRotateWebhookSecretData = {
    body?: never;
    path: {
        /**
         * Endpoint Id
         */
        endpoint_id: string;
    };
    query?: never;
    url: '/api/v1/admin/webhooks/{endpoint_id}/rotate-secret';
};

export type adminRotateWebhookSecretErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminRotateWebhookSecretError = adminRotateWebhookSecretErrors[keyof adminRotateWebhookSecretErrors];

export type adminRotateWebhookSecretResponses = {
    /**
     * Successful Response
     */
    200: WebhookCreated;
};

export type adminRotateWebhookSecretResponse = adminRotateWebhookSecretResponses[keyof adminRotateWebhookSecretResponses];

export type adminTestWebhookData = {
    body?: never;
    path: {
        /**
         * Endpoint Id
         */
        endpoint_id: string;
    };
    query?: never;
    url: '/api/v1/admin/webhooks/{endpoint_id}/test';
};

export type adminTestWebhookErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminTestWebhookError = adminTestWebhookErrors[keyof adminTestWebhookErrors];

export type adminTestWebhookResponses = {
    /**
     * Successful Response
     */
    202: Message;
};

export type adminTestWebhookResponse = adminTestWebhookResponses[keyof adminTestWebhookResponses];
