import csv
import hashlib
import io
import os
import tempfile
import uuid
from datetime import UTC, datetime, timedelta
from pathlib import Path

from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas
from sqlmodel import Session, col, select

from app.core.config import settings
from app.models import (
    CaseEvent,
    ExportJob,
    ExportKind,
    JobStatus,
    ServiceCase,
    ServiceCategory,
    User,
)


def neutralize_csv(value: object) -> str:
    text = "" if value is None else str(value)
    if text.startswith(("=", "+", "-", "@")):
        return "'" + text
    return text


def _write_atomic(data: bytes, suffix: str) -> tuple[str, int, str]:
    key = f"{uuid.uuid4().hex[:2]}/{uuid.uuid4().hex}.{suffix}"
    final_path = settings.DATA_ROOT / "exports" / key
    final_path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix="export-", dir=final_path.parent
    )
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary_name, final_path)
    except Exception:
        Path(temporary_name).unlink(missing_ok=True)
        raise
    return key, len(data), hashlib.sha256(data).hexdigest()


def render_case_pdf(session: Session, service_case: ServiceCase) -> bytes:
    category = session.get(ServiceCategory, service_case.category_id)
    assignee = (
        session.get(User, service_case.assigned_to_id)
        if service_case.assigned_to_id
        else None
    )
    output = io.BytesIO()
    pdf = canvas.Canvas(output, pagesize=LETTER, pageCompression=1)
    width, height = LETTER
    y = height - 54

    def line(label: str, value: object, *, gap: int = 18) -> None:
        nonlocal y
        if y < 72:
            pdf.showPage()
            y = height - 54
        pdf.setFont("Helvetica-Bold", 9)
        pdf.drawString(54, y, label)
        pdf.setFont("Helvetica", 9)
        pdf.drawString(170, y, str(value)[:95])
        y -= gap

    pdf.setTitle(f"Tahr Desk case {service_case.reference}")
    pdf.setFont("Helvetica-Bold", 20)
    pdf.drawString(54, y, "Tahr Desk case summary")
    y -= 32
    line("Reference", service_case.reference)
    line("Status", service_case.status)
    line("Priority", service_case.priority)
    line("Service", category.name if category else "Unknown")
    line("Reporter", service_case.reporter_name)
    line("Reporter email", service_case.reporter_email)
    line("Location", service_case.location_text)
    line("Assigned to", assignee.full_name if assignee else "Unassigned")
    line("Created", service_case.created_at.isoformat())
    line("Target resolution", service_case.target_resolution_at.isoformat())
    y -= 8
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(54, y, service_case.subject[:90])
    y -= 20
    pdf.setFont("Helvetica", 9)
    for paragraph in service_case.description.splitlines() or [""]:
        for start in range(0, len(paragraph), 95):
            pdf.drawString(54, y, paragraph[start : start + 95])
            y -= 14
    y -= 14
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(54, y, "Public timeline")
    y -= 20
    events = session.exec(
        select(CaseEvent)
        .where(
            CaseEvent.case_id == service_case.id,
            CaseEvent.visibility == "public",
        )
        .order_by(col(CaseEvent.created_at))
    ).all()
    for event in events:
        line(event.created_at.strftime("%Y-%m-%d %H:%M UTC"), event.summary, gap=15)
    pdf.setFont("Helvetica", 7)
    pdf.drawString(54, 36, "Generated by Tahr Desk. Private staff notes are excluded.")
    pdf.save()
    return output.getvalue()


def render_cases_csv(session: Session, filters: dict[str, object]) -> bytes:
    statement = (
        select(ServiceCase).order_by(col(ServiceCase.created_at).desc()).limit(50_001)
    )
    if status := filters.get("status"):
        statement = statement.where(ServiceCase.status == str(status))
    if priority := filters.get("priority"):
        statement = statement.where(ServiceCase.priority == str(priority))
    cases = session.exec(statement).all()
    if len(cases) > 50_000:
        raise RuntimeError("export_too_large")
    output = io.StringIO(newline="")
    writer = csv.writer(output)
    writer.writerow(
        [
            "reference",
            "status",
            "priority",
            "subject",
            "location",
            "reporter_name",
            "reporter_email",
            "created_at",
            "updated_at",
        ]
    )
    for item in cases:
        writer.writerow(
            [
                neutralize_csv(item.reference),
                neutralize_csv(item.status),
                neutralize_csv(item.priority),
                neutralize_csv(item.subject),
                neutralize_csv(item.location_text),
                neutralize_csv(item.reporter_name),
                neutralize_csv(item.reporter_email),
                item.created_at.isoformat(),
                item.updated_at.isoformat(),
            ]
        )
    return ("\ufeff" + output.getvalue()).encode("utf-8")


def process_export(session: Session, job: ExportJob) -> None:
    if job.kind == ExportKind.case_pdf:
        if job.case_id is None:
            raise RuntimeError("missing_case")
        service_case = session.get(ServiceCase, job.case_id)
        if service_case is None:
            raise RuntimeError("case_not_found")
        data = render_case_pdf(session, service_case)
        suffix = "pdf"
    else:
        data = render_cases_csv(session, job.filter_snapshot)
        suffix = "csv"
    key, byte_count, digest = _write_atomic(data, suffix)
    job.storage_key = key
    job.byte_count = byte_count
    job.sha256 = digest
    job.status = JobStatus.ready
    job.error_code = None
    job.expires_at = datetime.now(UTC) + timedelta(hours=24)
    job.lease_owner = None
    job.lease_expires_at = None
    job.updated_at = datetime.now(UTC)
    session.add(job)
    session.commit()
