/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicReportRouteImport } from './routes/_public/report'
import { Route as PublicTrackRouteImport } from './routes/_public/track'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminAccountRouteImport } from './routes/_admin/admin.account'
import { Route as AdminAdminAgentsRouteImport } from './routes/_admin/admin.agents'
import { Route as AdminAdminExportsRouteImport } from './routes/_admin/admin.exports'
import { Route as AdminAdminForbiddenRouteImport } from './routes/_admin/admin.forbidden'
import { Route as PublicServicesIndexRouteImport } from './routes/_public/services.index'
import { Route as PublicServicesSlugRouteImport } from './routes/_public/services.$slug'
import { Route as AdminAdminCasesIndexRouteImport } from './routes/_admin/admin.cases.index'
import { Route as AdminAdminCasesCaseIdRouteImport } from './routes/_admin/admin.cases.$caseId'
import { Route as AdminAdminSettingsGeneralRouteImport } from './routes/_admin/admin.settings.general'
import { Route as AdminAdminSettingsServicesRouteImport } from './routes/_admin/admin.settings.services'
import { Route as AdminAdminSettingsWebhooksRouteImport } from './routes/_admin/admin.settings.webhooks'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicReportRoute = PublicReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTrackRoute = PublicTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => PublicRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAccountRoute = AdminAdminAccountRouteImport.update({
  id: '/admin/account',
  path: '/admin/account',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAgentsRoute = AdminAdminAgentsRouteImport.update({
  id: '/admin/agents',
  path: '/admin/agents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminExportsRoute = AdminAdminExportsRouteImport.update({
  id: '/admin/exports',
  path: '/admin/exports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminForbiddenRoute = AdminAdminForbiddenRouteImport.update({
  id: '/admin/forbidden',
  path: '/admin/forbidden',
  getParentRoute: () => AdminRoute,
} as any)
const PublicServicesIndexRoute = PublicServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesSlugRoute = PublicServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const AdminAdminCasesIndexRoute = AdminAdminCasesIndexRouteImport.update({
  id: '/admin/cases/',
  path: '/admin/cases/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCasesCaseIdRoute = AdminAdminCasesCaseIdRouteImport.update({
  id: '/admin/cases/$caseId',
  path: '/admin/cases/$caseId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsGeneralRoute =
  AdminAdminSettingsGeneralRouteImport.update({
    id: '/admin/settings/general',
    path: '/admin/settings/general',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminSettingsServicesRoute =
  AdminAdminSettingsServicesRouteImport.update({
    id: '/admin/settings/services',
    path: '/admin/settings/services',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminSettingsWebhooksRoute =
  AdminAdminSettingsWebhooksRouteImport.update({
    id: '/admin/settings/webhooks',
    path: '/admin/settings/webhooks',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/report': typeof PublicReportRoute
  '/track': typeof PublicTrackRoute
  '/admin/account': typeof AdminAdminAccountRoute
  '/admin/agents': typeof AdminAdminAgentsRoute
  '/admin/exports': typeof AdminAdminExportsRoute
  '/admin/forbidden': typeof AdminAdminForbiddenRoute
  '/services/$slug': typeof PublicServicesSlugRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/services/': typeof PublicServicesIndexRoute
  '/admin/cases/$caseId': typeof AdminAdminCasesCaseIdRoute
  '/admin/settings/general': typeof AdminAdminSettingsGeneralRoute
  '/admin/settings/services': typeof AdminAdminSettingsServicesRoute
  '/admin/settings/webhooks': typeof AdminAdminSettingsWebhooksRoute
  '/admin/cases/': typeof AdminAdminCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/report': typeof PublicReportRoute
  '/track': typeof PublicTrackRoute
  '/admin/account': typeof AdminAdminAccountRoute
  '/admin/agents': typeof AdminAdminAgentsRoute
  '/admin/exports': typeof AdminAdminExportsRoute
  '/admin/forbidden': typeof AdminAdminForbiddenRoute
  '/services/$slug': typeof PublicServicesSlugRoute
  '/admin': typeof AdminAdminIndexRoute
  '/services': typeof PublicServicesIndexRoute
  '/admin/cases/$caseId': typeof AdminAdminCasesCaseIdRoute
  '/admin/settings/general': typeof AdminAdminSettingsGeneralRoute
  '/admin/settings/services': typeof AdminAdminSettingsServicesRoute
  '/admin/settings/webhooks': typeof AdminAdminSettingsWebhooksRoute
  '/admin/cases': typeof AdminAdminCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/_public/report': typeof PublicReportRoute
  '/_public/track': typeof PublicTrackRoute
  '/_public/': typeof PublicIndexRoute
  '/_admin/admin/account': typeof AdminAdminAccountRoute
  '/_admin/admin/agents': typeof AdminAdminAgentsRoute
  '/_admin/admin/exports': typeof AdminAdminExportsRoute
  '/_admin/admin/forbidden': typeof AdminAdminForbiddenRoute
  '/_public/services/$slug': typeof PublicServicesSlugRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_public/services/': typeof PublicServicesIndexRoute
  '/_admin/admin/cases/$caseId': typeof AdminAdminCasesCaseIdRoute
  '/_admin/admin/settings/general': typeof AdminAdminSettingsGeneralRoute
  '/_admin/admin/settings/services': typeof AdminAdminSettingsServicesRoute
  '/_admin/admin/settings/webhooks': typeof AdminAdminSettingsWebhooksRoute
  '/_admin/admin/cases/': typeof AdminAdminCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/report'
    | '/track'
    | '/admin/account'
    | '/admin/agents'
    | '/admin/exports'
    | '/admin/forbidden'
    | '/services/$slug'
    | '/admin/'
    | '/services/'
    | '/admin/cases/$caseId'
    | '/admin/settings/general'
    | '/admin/settings/services'
    | '/admin/settings/webhooks'
    | '/admin/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/report'
    | '/track'
    | '/admin/account'
    | '/admin/agents'
    | '/admin/exports'
    | '/admin/forbidden'
    | '/services/$slug'
    | '/admin'
    | '/services'
    | '/admin/cases/$caseId'
    | '/admin/settings/general'
    | '/admin/settings/services'
    | '/admin/settings/webhooks'
    | '/admin/cases'
  id:
    | '__root__'
    | '/_admin'
    | '/_public'
    | '/login'
    | '/_public/report'
    | '/_public/track'
    | '/_public/'
    | '/_admin/admin/account'
    | '/_admin/admin/agents'
    | '/_admin/admin/exports'
    | '/_admin/admin/forbidden'
    | '/_public/services/$slug'
    | '/_admin/admin/'
    | '/_public/services/'
    | '/_admin/admin/cases/$caseId'
    | '/_admin/admin/settings/general'
    | '/_admin/admin/settings/services'
    | '/_admin/admin/settings/webhooks'
    | '/_admin/admin/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/report': {
      id: '/_public/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof PublicReportRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/track': {
      id: '/_public/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof PublicTrackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/account': {
      id: '/_admin/admin/account'
      path: '/admin/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/agents': {
      id: '/_admin/admin/agents'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/exports': {
      id: '/_admin/admin/exports'
      path: '/admin/exports'
      fullPath: '/admin/exports'
      preLoaderRoute: typeof AdminAdminExportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/forbidden': {
      id: '/_admin/admin/forbidden'
      path: '/admin/forbidden'
      fullPath: '/admin/forbidden'
      preLoaderRoute: typeof AdminAdminForbiddenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/services/': {
      id: '/_public/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof PublicServicesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services/$slug': {
      id: '/_public/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof PublicServicesSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/admin/cases/': {
      id: '/_admin/admin/cases/'
      path: '/admin/cases'
      fullPath: '/admin/cases/'
      preLoaderRoute: typeof AdminAdminCasesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/cases/$caseId': {
      id: '/_admin/admin/cases/$caseId'
      path: '/admin/cases/$caseId'
      fullPath: '/admin/cases/$caseId'
      preLoaderRoute: typeof AdminAdminCasesCaseIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings/general': {
      id: '/_admin/admin/settings/general'
      path: '/admin/settings/general'
      fullPath: '/admin/settings/general'
      preLoaderRoute: typeof AdminAdminSettingsGeneralRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings/services': {
      id: '/_admin/admin/settings/services'
      path: '/admin/settings/services'
      fullPath: '/admin/settings/services'
      preLoaderRoute: typeof AdminAdminSettingsServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings/webhooks': {
      id: '/_admin/admin/settings/webhooks'
      path: '/admin/settings/webhooks'
      fullPath: '/admin/settings/webhooks'
      preLoaderRoute: typeof AdminAdminSettingsWebhooksRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminAccountRoute: typeof AdminAdminAccountRoute
  AdminAdminAgentsRoute: typeof AdminAdminAgentsRoute
  AdminAdminExportsRoute: typeof AdminAdminExportsRoute
  AdminAdminForbiddenRoute: typeof AdminAdminForbiddenRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminCasesCaseIdRoute: typeof AdminAdminCasesCaseIdRoute
  AdminAdminSettingsGeneralRoute: typeof AdminAdminSettingsGeneralRoute
  AdminAdminSettingsServicesRoute: typeof AdminAdminSettingsServicesRoute
  AdminAdminSettingsWebhooksRoute: typeof AdminAdminSettingsWebhooksRoute
  AdminAdminCasesIndexRoute: typeof AdminAdminCasesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAccountRoute: AdminAdminAccountRoute,
  AdminAdminAgentsRoute: AdminAdminAgentsRoute,
  AdminAdminExportsRoute: AdminAdminExportsRoute,
  AdminAdminForbiddenRoute: AdminAdminForbiddenRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminCasesCaseIdRoute: AdminAdminCasesCaseIdRoute,
  AdminAdminSettingsGeneralRoute: AdminAdminSettingsGeneralRoute,
  AdminAdminSettingsServicesRoute: AdminAdminSettingsServicesRoute,
  AdminAdminSettingsWebhooksRoute: AdminAdminSettingsWebhooksRoute,
  AdminAdminCasesIndexRoute: AdminAdminCasesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PublicRouteChildren {
  PublicReportRoute: typeof PublicReportRoute
  PublicTrackRoute: typeof PublicTrackRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicServicesSlugRoute: typeof PublicServicesSlugRoute
  PublicServicesIndexRoute: typeof PublicServicesIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicReportRoute: PublicReportRoute,
  PublicTrackRoute: PublicTrackRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicServicesSlugRoute: PublicServicesSlugRoute,
  PublicServicesIndexRoute: PublicServicesIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
